package sn.ucad.master.assurance.bo;
// Generated 27 mars 2019 17:47:55 by Hibernate Tools 4.3.1


import java.util.Collection;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;




/**
 * Assure generated by hbm2java
 */
@Entity
@Table(name="assure")
public class Assure  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Id_Assure", unique=true, nullable=false)
	private int idAssure;
	@Column(name="Nom_Assure", nullable=false, length=30)
     private String nomAssure;
	 @Column(name="Prenom_Assure", nullable=false, length=30)
     private String prenomAssure;
	 @Column(name="Adresse_Assure", length=60)
     private String adresseAssure;
	 @Column(name="Telephone", nullable=false)
     private int telephone;
     @OneToMany(fetch=FetchType.LAZY, mappedBy="assure")
     private Collection<Contrat> contrats ;

    public Assure() {
    }

	
    public Assure(int idAssure, String nomAssure, String prenomAssure, int telephone) {
        this.idAssure = idAssure;
        this.nomAssure = nomAssure;
        this.prenomAssure = prenomAssure;
        this.telephone = telephone;
    }
    
    public Assure(int idAssure, String nomAssure, String prenomAssure, String adresseAssure, int telephone,
			Collection<Contrat> contrats) {
		super();
		this.idAssure = idAssure;
		this.nomAssure = nomAssure;
		this.prenomAssure = prenomAssure;
		this.adresseAssure = adresseAssure;
		this.telephone = telephone;
		this.contrats = contrats;
	}
     
    public int getIdAssure() {
        return this.idAssure;
    }
    
    public void setIdAssure(int idAssure) {
        this.idAssure = idAssure;
    }
    public String getNomAssure() {
        return this.nomAssure;
    }
    
    public void setNomAssure(String nomAssure) {
        this.nomAssure = nomAssure;
    }

    
   
    public String getPrenomAssure() {
        return this.prenomAssure;
    }
    
    public void setPrenomAssure(String prenomAssure) {
        this.prenomAssure = prenomAssure;
    }

    
    
    public String getAdresseAssure() {
        return this.adresseAssure;
    }
    
    public void setAdresseAssure(String adresseAssure) {
        this.adresseAssure = adresseAssure;
    }

    
    
    public int getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(int telephone) {
        this.telephone = telephone;
    }


	public Collection<Contrat> getContrats() {
		return contrats;
	}


	public void setContrats(Collection<Contrat> contrats) {
		this.contrats = contrats;
	}
    
    

}


