package sn.ucad.master.assurance.bo;
// Generated 27 mars 2019 17:47:55 by Hibernate Tools 4.3.1


import java.util.Collection;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name="categorie")
public class Categorie  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
   @Id 
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name="Id_categorie", unique=true, nullable=false)
   private int idCategorie;
   @Column(name="Libelle", nullable=false, length=60)
   private String libelle;
   @OneToMany(fetch=FetchType.LAZY, mappedBy="categorie")
   private Collection<Vehicule> vehicules;

    public Categorie() {
    }

	
    public Categorie(int idCategorie, String libelle) {
        this.idCategorie = idCategorie;
        this.libelle = libelle;
    }
    
    public Categorie(int idCategorie, String libelle, Collection<Vehicule> vehicules) {
		super();
		this.idCategorie = idCategorie;
		this.libelle = libelle;
		this.vehicules = vehicules;
	}


	/*public Categorie(int idCategorie, String libelle, Set<Vehicule> vehicules) {
       this.idCategorie = idCategorie;
       this.libelle = libelle;
       this.vehicules = vehicules;
    }*/
   
     
    public int getIdCategorie() {
        return this.idCategorie;
    }
    
    public void setIdCategorie(int idCategorie) {
        this.idCategorie = idCategorie;
    }

    
    
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }


	public Collection<Vehicule> getVehicules() {
		return vehicules;
	}


	public void setVehicules(Collection<Vehicule> vehicules) {
		this.vehicules = vehicules;
	}


    



}


