package sn.ucad.master.assurance.bo;
// Generated 27 mars 2019 17:47:55 by Hibernate Tools 4.3.1


import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contrat generated by hbm2java
 */
@Entity
@Table(name="contrat")
public class Contrat  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	 @Id 

	 @GeneratedValue(strategy=GenerationType.IDENTITY)
	 @Column(name="Id_contrat", unique=true, nullable=false)
	 private int idContrat;
	 @ManyToOne(fetch=FetchType.LAZY)
	 @JoinColumn(name="Id_Assure")
     private Assure assure;
	 @ManyToOne(fetch=FetchType.LAZY)
	 @JoinColumn(name="Code_App")
     private Apporteur apporteur;
	 @ManyToOne(fetch=FetchType.LAZY)
	 @JoinColumn(name="Id_service", nullable=false)
     private Service service;
	 @ManyToOne(fetch=FetchType.LAZY)
	 @JoinColumn(name="Id_Souscripeur")
     private Souscripteur souscripteur;
	 @Column(name="referance", nullable=false, length=30)
     private String referance;
	@Column(name="Date_creation", nullable=false, length=19)
     private String dateCreation;
	 @Column(name="Date_debut", nullable=false, length=19)
     private String dateDebut;
	 @Column(name="Date_fin", nullable=false, length=19)
     private String dateFin;
	 @Column(name="duree", nullable=false, length=10)
	 private Integer duree;
	 @OneToMany(fetch=FetchType.LAZY, mappedBy="contrat")
     private Collection<Detail> details;
     @OneToMany(fetch=FetchType.LAZY, mappedBy="contrat")
     private Collection<Avenant> avenants;
     @OneToMany(fetch=FetchType.LAZY, mappedBy="contrat")
     private Collection<Prime> primes;
    public Contrat() {
    	
    }
    
    
    public Contrat(int idContrat, Assure assure, Apporteur apporteur, Service service, Souscripteur souscripteur,
			String referance, String dateCreation, String dateDebut, String dateFin, Integer duree,
			Collection<Detail> details, Collection<Avenant> avenants, Collection<Prime> primes) {
		super();
		this.idContrat = idContrat;
		this.assure = assure;
		this.apporteur = apporteur;
		this.service = service;
		this.souscripteur = souscripteur;
		this.referance = referance;
		this.dateCreation = dateCreation;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.duree = duree;
		this.details = details;
		this.avenants = avenants;
		this.primes = primes;
	}



	public Contrat(int idContrat, Service service, String referance, String dateCreation, String dateDebut, String dateFin,Integer duree) {
        this.idContrat = idContrat;
        this.service = service;
        this.referance = referance;
        this.dateCreation = dateCreation;
        this.dateDebut = dateDebut;
        this.dateFin = dateFin;
        this.duree=duree;
    }
    /*public Contrat(int idContrat, Assure assure, Service service, Souscripteur souscripteur, String referance, Date dateCreation, Date dateDebut, Date dateFin, Set<Detail> details, Set<Avenant> avenants, Set<Prime> primes) {
       this.idContrat = idContrat;
       this.assure = assure;
       this.service = service;
       this.souscripteur = souscripteur;
       this.referance = referance;
       this.dateCreation = dateCreation;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.details = details;
       this.avenants = avenants;
       this.primes = primes;
    }*/
   
    
    public Contrat(int idContrat, Assure assure, Service service, Souscripteur souscripteur, String referance,
			String dateCreation, String dateDebut, String dateFin,Integer duree, Collection<Detail> details, Collection<Avenant> avenants,
			Collection<Prime> primes) {
		super();
		this.idContrat = idContrat;
		this.assure = assure;
		this.service = service;
		this.souscripteur = souscripteur;
		this.referance = referance;
		this.dateCreation = dateCreation;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.details = details;
		this.avenants = avenants;
		this.primes = primes;
		this.duree=duree;
	}


	public int getIdContrat() {
        return this.idContrat;
    }
    
    public void setIdContrat(int idContrat) {
        this.idContrat = idContrat;
    }


    public Assure getAssure() {
        return this.assure;
    }
    
    public void setAssure(Assure assure) {
        this.assure = assure;
    }

    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }


    public Souscripteur getSouscripteur() {
        return this.souscripteur;
    }
    
    public void setSouscripteur(Souscripteur souscripteur) {
        this.souscripteur = souscripteur;
    }
    public String getReferance() {
        return this.referance;
    }
    
    public void setReferance(String referance) {
        this.referance = referance;
    }

    
    public String getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(String dateCreation) {
        this.dateCreation = dateCreation;
    }

    
    public String getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(String dateDebut) {
        this.dateDebut = dateDebut;
    }

    
    public String getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(String dateFin) {
        this.dateFin = dateFin;
    }
    
	public Integer getDuree() {
		return duree;
	}


	public void setDuree(Integer duree) {
		this.duree = duree;
	}


	public Collection<Detail> getDetails() {
		return details;
	}


	public void setDetails(Collection<Detail> details) {
		this.details = details;
	}


	public Collection<Avenant> getAvenants() {
		return avenants;
	}


	public void setAvenants(Collection<Avenant> avenants) {
		this.avenants = avenants;
	}


	public Collection<Prime> getPrimes() {
		return primes;
	}


	public void setPrimes(Collection<Prime> primes) {
		this.primes = primes;
	}


	public Apporteur getApporteur() {
		return apporteur;
	}


	public void setApporteur(Apporteur apporteur) {
		this.apporteur = apporteur;
	}


    



}


