package sn.ucad.master.assurance.bo;
// Generated 27 mars 2019 17:47:55 by Hibernate Tools 4.3.1


import java.util.Collection;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Garantie generated by hbm2java
 */
@Entity
@Table(name="garantie")
public class Garantie  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Id_garantie", unique=true, nullable=false)
	private int idGarantie;
	@Column(name="Libelle_garantie", nullable=false, length=60)
    private String libelleGarantie;
	@Column(name="Prime_brute",nullable=false)
    private Integer primeBrute;
	@OneToMany(fetch=FetchType.LAZY, mappedBy="garantie")
    private Collection<Detail> details;

    public Garantie() {
    }

	
    public Garantie(int idGarantie, String libelleGarantie,Integer primeBrute) {
        this.idGarantie = idGarantie;
        this.libelleGarantie = libelleGarantie;
        this.primeBrute= primeBrute;
    }
    
    /*public Garantie(int idGarantie, String libelleGarantie, Set<Detail> details) {
       this.idGarantie = idGarantie;
       this.libelleGarantie = libelleGarantie;
       this.details = details;
    }*/
    
     
    public Garantie(int idGarantie, String libelleGarantie,Integer primeBrute, Collection<Detail> details) {
		super();
		this.idGarantie = idGarantie;
		this.libelleGarantie = libelleGarantie;
		 this.primeBrute= primeBrute;
		this.details = details;
	}


	public int getIdGarantie() {
        return this.idGarantie;
    }
    
    public void setIdGarantie(int idGarantie) {
        this.idGarantie = idGarantie;
    }

    
    
    public String getLibelleGarantie() {
        return this.libelleGarantie;
    }
    
    public void setLibelleGarantie(String libelleGarantie) {
        this.libelleGarantie = libelleGarantie;
    }


	public Collection<Detail> getDetails() {
		return details;
	}


	public void setDetails(Collection<Detail> details) {
		this.details = details;
	}


	public Integer getPrimeBrute() {
		return primeBrute;
	}


	public void setPrimeBrute(Integer primeBrute) {
		this.primeBrute = primeBrute;
	}
	

}


