package sn.ucad.master.assurance.bo;
// Generated 27 mars 2019 17:47:55 by Hibernate Tools 4.3.1


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Habitation generated by hbm2java
 */
@Entity
@Table(name="habitation")
@DiscriminatorValue("HABITATION")
public class Habitation extends Service implements Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	 /*@Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
     @Column(name="Idhabitat", unique=true, nullable=false)
	 private int idhabitat;*/
//	 @ManyToOne(fetch=FetchType.LAZY)
//	 @JoinColumn(name="Id_service")
     /*private Service service;*/
	 @Column(name="Superficie")
     private Integer superficie;
	 @Column(name="Adresse", length=254)
     private String adresse;
	 @Column(name="Mtn_acquisition")
     private Integer mtnAcquisition;
	 @Column(name="Type_batiment", length=254)
     private String typeBatiment;
	 @Column(name="nbre_piece")
     private Integer nbrePiece;

    public Habitation() {
    	super();
    }
    
    

	
//    public Habitation(int idhabitat) {
//        this.idhabitat = idhabitat;
//    }
   /* public Habitation(int idhabitat, Service service, Integer superficie, String adresse, Integer mtnAcquisition, String typeBatiment, Integer nbrePiece) {
       this.idhabitat = idhabitat;
       this.service = service;
       this.superficie = superficie;
       this.adresse = adresse;
       this.mtnAcquisition = mtnAcquisition;
       this.typeBatiment = typeBatiment;
       this.nbrePiece = nbrePiece;
    }*/
   
     
    /*public int getIdhabitat() {
        return this.idhabitat;
    }
    
    public void setIdhabitat(int idhabitat) {
        this.idhabitat = idhabitat;
    }
*/
    
    public Habitation(Integer superficie, String adresse, Integer mtnAcquisition, String typeBatiment,
			Integer nbrePiece) {
		super();
		this.superficie = superficie;
		this.adresse = adresse;
		this.mtnAcquisition = mtnAcquisition;
		this.typeBatiment = typeBatiment;
		this.nbrePiece = nbrePiece;
	}


	public Habitation(int idService, String referenceservice, Integer superficie, String adresse, Integer mtnAcquisition,
		String typeBatiment, Integer nbrePiece) {
	super(idService, referenceservice);
	this.superficie = superficie;
	this.adresse = adresse;
	this.mtnAcquisition = mtnAcquisition;
	this.typeBatiment = typeBatiment;
	this.nbrePiece = nbrePiece;
}




	public Habitation(int idService, Integer superficie, String adresse, Integer mtnAcquisition, String typeBatiment,
			Integer nbrePiece) {
		super(idService);
		this.superficie = superficie;
		this.adresse = adresse;
		this.mtnAcquisition = mtnAcquisition;
		this.typeBatiment = typeBatiment;
		this.nbrePiece = nbrePiece;
	}




	public Habitation(int idService) {
		super(idService);
		// TODO Auto-generated constructor stub
	}




	/*public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }*/

    
    
    public Integer getSuperficie() {
        return this.superficie;
    }
    
    public void setSuperficie(Integer superficie) {
        this.superficie = superficie;
    }

    
    
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    
    public Integer getMtnAcquisition() {
        return this.mtnAcquisition;
    }
    
    public void setMtnAcquisition(Integer mtnAcquisition) {
        this.mtnAcquisition = mtnAcquisition;
    }

    
    
    public String getTypeBatiment() {
        return this.typeBatiment;
    }
    
    public void setTypeBatiment(String typeBatiment) {
        this.typeBatiment = typeBatiment;
    }

    
    
    public Integer getNbrePiece() {
        return this.nbrePiece;
    }
    
    public void setNbrePiece(Integer nbrePiece) {
        this.nbrePiece = nbrePiece;
    }




}


