package sn.ucad.master.assurance.bo;
// Generated 27 mars 2019 17:47:55 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Pret generated by hbm2java
 */
@Entity
@Table(name="pret")
@DiscriminatorValue("PRET")
public class Pret extends Service  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/*@Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="Id_Pret", unique=true, nullable=false)
	private int idPret;*/
	/*@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_service")
    private Service service;*/
	@Column(name="Mtn_Pret")
    private Integer mtnPret;
    @Column(name="Date_Pret", length=19)
    private String datePret;
	@Column(name="Nom_organisme", length=54)
    private String nomOrganisme;

    public Pret() {
    }

	
    /*public Pret(int idPret) {
        this.idPret = idPret;
    }
    public Pret(int idPret, Service service, Integer mtnPret, String datePret, String nomOrganisme) {
       this.idPret = idPret;
       this.service = service;
       this.mtnPret = mtnPret;
       this.datePret = datePret;
       this.nomOrganisme = nomOrganisme;
    }*/
   
     
   /* public int getIdPret() {
        return this.idPret;
    }
    
    public void setIdPret(int idPret) {
        this.idPret = idPret;
    }*/


    /*public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }*/

    
    
    public Integer getMtnPret() {
        return this.mtnPret;
    }
    
    public Pret(int idService, String referenceservice, Integer mtnPret, String datePret, String nomOrganisme) {
		super(idService, referenceservice);
		this.mtnPret = mtnPret;
		this.datePret = datePret;
		this.nomOrganisme = nomOrganisme;
	}


	public Pret(int idService, Integer mtnPret, String datePret, String nomOrganisme) {
		super(idService);
		this.mtnPret = mtnPret;
		this.datePret = datePret;
		this.nomOrganisme = nomOrganisme;
	}


	public Pret(Integer mtnPret, String datePret, String nomOrganisme) {
		super();
		this.mtnPret = mtnPret;
		this.datePret = datePret;
		this.nomOrganisme = nomOrganisme;
	}


	public void setMtnPret(Integer mtnPret) {
        this.mtnPret = mtnPret;
    }

    
    public String getDatePret() {
        return this.datePret;
    }
    
    public void setDatePret(String datePret) {
        this.datePret = datePret;
    }

    
    
    public String getNomOrganisme() {
        return this.nomOrganisme;
    }
    
    public void setNomOrganisme(String nomOrganisme) {
        this.nomOrganisme = nomOrganisme;
    }




}


