package sn.ucad.master.assurance.bo;
// Generated 27 mars 2019 17:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Prime generated by hbm2java
 */
@Entity
@Table(name="prime")
public class Prime  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="Id_Prime", unique=true, nullable=false)
	private int idPrime;
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_contrat")
    private Contrat contrat;
	@Column(name="Prime_annuel")
    private Integer primeAnnuel;
	@Column(name="FGA")
    private Integer fga;
	@Column(name="Taxes")
    private Integer taxes;
	@Column(name="Frais_accessoires")
    private Integer fraisAccessoires;
	@Column(name="Prime_TTC")
    private Integer primeTtc;
	@Column(name="Commission")
    private Integer commission;
	@Column(name="Prime_nette")
    private Integer primeNette;

    public Prime() {
    }

	
    public Prime(int idPrime) {
        this.idPrime = idPrime;
    }
    public Prime(int idPrime, Contrat contrat, Integer primeAnnuel, Integer fga, Integer taxes, Integer fraisAccessoires, Integer primeTtc, Integer commission, Integer primeNette) {
       this.idPrime = idPrime;
       this.contrat = contrat;
       this.primeAnnuel = primeAnnuel;
       this.fga = fga;
       this.taxes = taxes;
       this.fraisAccessoires = fraisAccessoires;
       this.primeTtc = primeTtc;
       this.commission = commission;
       this.primeNette = primeNette;
    }
   
     
    public int getIdPrime() {
        return this.idPrime;
    }
    
    public void setIdPrime(int idPrime) {
        this.idPrime = idPrime;
    }


    public Contrat getContrat() {
        return this.contrat;
    }
    
    public void setContrat(Contrat contrat) {
        this.contrat = contrat;
    }

    
    
    public Integer getPrimeAnnuel() {
        return this.primeAnnuel;
    }
    
    public void setPrimeAnnuel(Integer primeAnnuel) {
        this.primeAnnuel = primeAnnuel;
    }

    
    
    public Integer getFga() {
        return this.fga;
    }
    
    public void setFga(Integer fga) {
        this.fga = fga;
    }

    
    
    public Integer getTaxes() {
        return this.taxes;
    }
    
    public void setTaxes(Integer taxes) {
        this.taxes = taxes;
    }

    
    
    public Integer getFraisAccessoires() {
        return this.fraisAccessoires;
    }
    
    public void setFraisAccessoires(Integer fraisAccessoires) {
        this.fraisAccessoires = fraisAccessoires;
    }

    
    
    public Integer getPrimeTtc() {
        return this.primeTtc;
    }
    
    public void setPrimeTtc(Integer primeTtc) {
        this.primeTtc = primeTtc;
    }

    
    
    public Integer getCommission() {
        return this.commission;
    }
    
    public void setCommission(Integer commission) {
        this.commission = commission;
    }

    
    
    public Integer getPrimeNette() {
        return this.primeNette;
    }
    
    public void setPrimeNette(Integer primeNette) {
        this.primeNette = primeNette;
    }




}


