package sn.ucad.master.assurance.bo;
// Generated 27 mars 2019 17:47:55 by Hibernate Tools 4.3.1


import java.util.Collection;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Souscripteur generated by hbm2java
 */
@Entity
@Table(name="souscripteur")
public class Souscripteur  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	 @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
     @Column(name="Id_Souscripeur", nullable=false)
	 private int idSouscripeur;
	 @Column(name="Nom_Souscripteur", length=50)
     private String nomSouscripteur;
	 @Column(name="Prenom_Souscripteur", length=50)
     private String prenomSouscripteur;
	 @Column(name="Adresse_Souscripteur", length=54)
     private String adresseSouscripteur;
	 @Column(name="Telephone_Souscripteur")
     private Integer telephoneSouscripteur;
	 @Column(name="Adresse_Mail", length=50)
     private String adresseMail;
	 @OneToMany(fetch=FetchType.LAZY, mappedBy="souscripteur")
     private Collection<Contrat> contrats;

    public Souscripteur() {
    }

	
    public Souscripteur(int idSouscripeur) {
        this.idSouscripeur = idSouscripeur;
    }
    /*public Souscripteur(int idSouscripeur, String nomSouscripteur, String prenomSouscripteur, String adresseSouscripteur, Integer telephoneSouscripteur, String adresseMail, Set<Contrat> contrats) {
       this.idSouscripeur = idSouscripeur;
       this.nomSouscripteur = nomSouscripteur;
       this.prenomSouscripteur = prenomSouscripteur;
       this.adresseSouscripteur = adresseSouscripteur;
       this.telephoneSouscripteur = telephoneSouscripteur;
       this.adresseMail = adresseMail;
       this.contrats = contrats;
    }*/
    
    public Souscripteur(int idSouscripeur, String nomSouscripteur, String prenomSouscripteur,String adresseSouscripteur, Integer telephoneSouscripteur, String adresseMail,Collection<Contrat> contrats) {
		super();
		this.idSouscripeur = idSouscripeur;
		this.nomSouscripteur = nomSouscripteur;
		this.prenomSouscripteur = prenomSouscripteur;
		this.adresseSouscripteur = adresseSouscripteur;
		this.telephoneSouscripteur = telephoneSouscripteur;
		this.adresseMail = adresseMail;
		this.contrats = contrats;
	}
    
    
    public int getIdSouscripeur() {
        return this.idSouscripeur;
    }
    
	public void setIdSouscripeur(int idSouscripeur) {
        this.idSouscripeur = idSouscripeur;
    }

    public String getNomSouscripteur() {
        return this.nomSouscripteur;
    }
    
    public void setNomSouscripteur(String nomSouscripteur) {
        this.nomSouscripteur = nomSouscripteur;
    }

    
   
    public String getPrenomSouscripteur() {
        return this.prenomSouscripteur;
    }
    
    public void setPrenomSouscripteur(String prenomSouscripteur) {
        this.prenomSouscripteur = prenomSouscripteur;
    }

    
    
    public String getAdresseSouscripteur() {
        return this.adresseSouscripteur;
    }
    
    public void setAdresseSouscripteur(String adresseSouscripteur) {
        this.adresseSouscripteur = adresseSouscripteur;
    }

    
    
    public Integer getTelephoneSouscripteur() {
        return this.telephoneSouscripteur;
    }
    
    public void setTelephoneSouscripteur(Integer telephoneSouscripteur) {
        this.telephoneSouscripteur = telephoneSouscripteur;
    }

    
    
    public String getAdresseMail() {
        return this.adresseMail;
    }
    
    public void setAdresseMail(String adresseMail) {
        this.adresseMail = adresseMail;
    }


	public Collection<Contrat> getContrats() {
		return contrats;
	}


	public void setContrats(Collection<Contrat> contrats) {
		this.contrats = contrats;
	}
    
    




}


