package sn.ucad.master.assurance.bo;
// Generated 27 mars 2019 17:47:55 by Hibernate Tools 4.3.1


import java.util.Collection;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeAvenant generated by hbm2java
 */
@Entity
@Table(name="type_avenant")
public class TypeAvenant  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="Id_Type", nullable=false)
	private int idType;
	@Column(name="Libelle_Type", length=50)
    private String libelleType;
	@OneToMany(fetch=FetchType.LAZY, mappedBy="typeAvenant")
    private Collection<Avenant> avenants;

    public TypeAvenant() {
    }

	
    public TypeAvenant(int idType) {
        this.idType = idType;
    }
    /*public TypeAvenant(int idType, String libelleType, Set<Avenant> avenants) {
       this.idType = idType;
       this.libelleType = libelleType;
       this.avenants = avenants;
    }*/
    
    public TypeAvenant(int idType, String libelleType, Collection<Avenant> avenants) {
		this.idType = idType;
		this.libelleType = libelleType;
		this.avenants = avenants;
	}
    
    public int getIdType() {
        return this.idType;
    }

	public void setIdType(int idType) {
        this.idType = idType;
    }

    
    
    public String getLibelleType() {
        return this.libelleType;
    }
    
    public void setLibelleType(String libelleType) {
        this.libelleType = libelleType;
    }


	public Collection<Avenant> getAvenants() {
		return avenants;
	}


	public void setAvenants(Collection<Avenant> avenants) {
		this.avenants = avenants;
	}




}


