package sn.ucad.master.assurance.bo;
// Generated 27 mars 2019 17:47:55 by Hibernate Tools 4.3.1



import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vehicule generated by hbm2java
 */
@Entity
@Table(name="VEHICULE")
@DiscriminatorValue("VEHICULE")
public class Vehicule extends Service  implements Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	//@Id 
    //@GeneratedValue(strategy=GenerationType.IDENTITY) 
    @Column(name="Matricule", /*unique=true,*/ /*nullable=false,*/ length=50)
	private String matricule;
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_categorie")
    private Categorie categorie;
	/*@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_service")
    private Service service;*/
	@Column(name="Marque", length=30)
    private String marque;
	@Column(name="Puissance")
    private Integer puissance;
	@Column(name="Energie", length=9)
    private String energie;
	@Column(name="Nbre_place")
    private Integer nbrePlace;
    @Column(name="Date_mise_circulation", length=19)
    private String dateMiseCirculation;
	@Column(name="Modele", length=50)
    private String modele;
	@Column(name="Charge_utile", length=18)
    private String chargeUtile;
	@Column(name="Valeur_neuve")
    private Integer valeurNeuve;
	@Column(name="Valeur_venale")
    private Integer valeurVenale;
	@Column(name="Cylindre")
    private Integer cylindre;
	@Column(name="Chassis")
    private Integer chassis;

    public Vehicule() {
    	super();
    }

	
    /*public Vehicule(String matricule) {
        this.matricule = matricule;
    }*/
    /*public Vehicule(String matricule, Categorie categorie, Service service, String marque, Integer puissance, String energie, Integer nbrePlace, String dateMiseCirculation, String modele, String chargeUtile, Integer valeurNeuve, Integer valeurVenale, Integer cylindre, Integer chassis) {
       this.matricule = matricule;
       this.categorie = categorie;
       this.service = service;
       this.marque = marque;
       this.puissance = puissance;
       this.energie = energie;
       this.nbrePlace = nbrePlace;
       this.dateMiseCirculation = dateMiseCirculation;
       this.modele = modele;
       this.chargeUtile = chargeUtile;
       this.valeurNeuve = valeurNeuve;
       this.valeurVenale = valeurVenale;
       this.cylindre = cylindre;
       this.chassis = chassis;
    }*/
   
     
    public String getMatricule() {
        return this.matricule;
    }
    
    
	public Vehicule(int idService, String matricule, Categorie categorie, String marque, Integer puissance,
			String energie, Integer nbrePlace, String dateMiseCirculation, String modele, String chargeUtile,
			Integer valeurNeuve, Integer valeurVenale, Integer cylindre, Integer chassis) {
		super(idService);
		this.matricule = matricule;
		this.categorie = categorie;
		this.marque = marque;
		this.puissance = puissance;
		this.energie = energie;
		this.nbrePlace = nbrePlace;
		this.dateMiseCirculation = dateMiseCirculation;
		this.modele = modele;
		this.chargeUtile = chargeUtile;
		this.valeurNeuve = valeurNeuve;
		this.valeurVenale = valeurVenale;
		this.cylindre = cylindre;
		this.chassis = chassis;
	}
    
    


	public Vehicule(int idService, String referenceservice, String matricule, Categorie categorie, String marque,
			Integer puissance, String energie, Integer nbrePlace, String dateMiseCirculation, String modele,
			String chargeUtile, Integer valeurNeuve, Integer valeurVenale, Integer cylindre, Integer chassis) {
		super(idService, referenceservice);
		this.matricule = matricule;
		this.categorie = categorie;
		this.marque = marque;
		this.puissance = puissance;
		this.energie = energie;
		this.nbrePlace = nbrePlace;
		this.dateMiseCirculation = dateMiseCirculation;
		this.modele = modele;
		this.chargeUtile = chargeUtile;
		this.valeurNeuve = valeurNeuve;
		this.valeurVenale = valeurVenale;
		this.cylindre = cylindre;
		this.chassis = chassis;
	}


	public Vehicule(String matricule, Categorie categorie, String marque, Integer puissance, String energie,
			Integer nbrePlace, String dateMiseCirculation, String modele, String chargeUtile, Integer valeurNeuve,
			Integer valeurVenale, Integer cylindre, Integer chassis) {
		super();
		this.matricule = matricule;
		this.categorie = categorie;
		this.marque = marque;
		this.puissance = puissance;
		this.energie = energie;
		this.nbrePlace = nbrePlace;
		this.dateMiseCirculation = dateMiseCirculation;
		this.modele = modele;
		this.chargeUtile = chargeUtile;
		this.valeurNeuve = valeurNeuve;
		this.valeurVenale = valeurVenale;
		this.cylindre = cylindre;
		this.chassis = chassis;
	}


	public void setMatricule(String matricule) {
        this.matricule = matricule;
    }


    public Categorie getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }


   /* public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }*/

    
    
    public String getMarque() {
        return this.marque;
    }
    
    public void setMarque(String marque) {
        this.marque = marque;
    }

    
    
    public Integer getPuissance() {
        return this.puissance;
    }
    
    public void setPuissance(Integer puissance) {
        this.puissance = puissance;
    }

    
    
    public String getEnergie() {
        return this.energie;
    }
    
    public void setEnergie(String energie) {
        this.energie = energie;
    }

    
    
    public Integer getNbrePlace() {
        return this.nbrePlace;
    }
    
    public void setNbrePlace(Integer nbrePlace) {
        this.nbrePlace = nbrePlace;
    }

    
    public String getDateMiseCirculation() {
        return this.dateMiseCirculation;
    }
    
    public void setDateMiseCirculation(String dateMiseCirculation) {
        this.dateMiseCirculation = dateMiseCirculation;
    }

    
    
    public String getModele() {
        return this.modele;
    }
    
    public void setModele(String modele) {
        this.modele = modele;
    }

    
    
    public String getChargeUtile() {
        return this.chargeUtile;
    }
    
    public void setChargeUtile(String chargeUtile) {
        this.chargeUtile = chargeUtile;
    }

    
    
    public Integer getValeurNeuve() {
        return this.valeurNeuve;
    }
    
    public void setValeurNeuve(Integer valeurNeuve) {
        this.valeurNeuve = valeurNeuve;
    }

    
    
    public Integer getValeurVenale() {
        return this.valeurVenale;
    }
    
    public void setValeurVenale(Integer valeurVenale) {
        this.valeurVenale = valeurVenale;
    }

    
    
    public Integer getCylindre() {
        return this.cylindre;
    }
    
    public void setCylindre(Integer cylindre) {
        this.cylindre = cylindre;
    }

    
    
    public Integer getChassis() {
        return this.chassis;
    }
    
    public void setChassis(Integer chassis) {
        this.chassis = chassis;
    }




}


